odom_filter:
  frequency: 50
  odom0: odom_raw
  odom0_config: [false, false, false,  # x, y, z
                 false, false, false,  # roll, pitch, yaw
                 true, true, true,     # vx, vy, vz
                 false, false, false,   # vroll, vpitch, vyaw NOTE: yaw might be erroneous, do not use for the moment
                 false, false, false]  # ax, ay, az
  odom0_differential: false

  imu0: imu/data
  imu0_config: [false, false, false,  # x, y, z
                true, true, true,     # roll, pitch, yaw
                false, false, false,  # vx, vy, vz
                false, false, false,     # vroll, vpitch, vyaw NOTE: Don't get valid data here currently, ignore
                false, false, false]   # ax, ay, az
  imu0_differential: false #fusing absolute position or orientation data should be done differentially-->
  
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom