camera_name: cam_right
resolution: [1504, 1504]
#frame_id: camera360_right_optical_frame
#camera_ns: /camera360/right
#rostopic: /camera360/right/image_raw # currently not used
camera_model: omni
distortion_model: radtan
distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
#distortion_coeffs: [-0.20450696, 0.23783403, -0.0006362, 0.0001414] #[0.0, 0.0, 0.0, 0.0]
#intrinsics: [1.56474378, 1231.98328921, 1229.77657257, 751.14563617,753.13315535] #[0.9997, 752, 752, 752.5, 752.5]
intrinsics: [1.570796, 1215.0, 1215.0, 752.5, 752.5]
mask_path: $(find hector_sensor_proc_launch)/config/kalibr_calibrations/camera360_webots/camera360_right_mask.png
