submap_service: "/elevation_mapping/get_submap"
map_frame_id: "world"
robot_frame_id: "base_link"
min_update_rate: 1.0
map_center_x: 0.0
map_center_y: 0.0
map_length_x: 10.0
map_length_y: 10.0
footprint_yaw: 0.7854
max_gap_width: 0.3
